
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: halfi-postgres
    restart: always
    environment:
      POSTGRES_USER: HalfiPostgres
      POSTGRES_PASSWORD: na4uih245huvz13ie9_iovjoid34_23dsacxz
      POSTGRES_DB: halfi_user_db
    ports:
      - "5433:5432"
    volumes:
      - halfi_user_data:/var/lib/postgresql/data

volumes:
  halfi_user_data: