server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA routing: любой роут отдаёт index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # (опционально) Проксирование API на бэк, если захотите единый домен
  # location /api/ {
  #   proxy_pass http://backend:8080;
  # }
}
