server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8080 
          predicates:
            - Path=/api/auth/** 
        - id: user-service-route
          uri: http://user-service:8080
          predicates:
            - Path=/api/user/**
        - id: profile-service-route
          uri: http://profile-service:8080
          predicates:
            - Path=/api/profile/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true