server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/halfi_user_db
spring.datasource.username=HalfiPostgres
spring.datasource.password=na4uih245huvz13ie9_iovjoid34_23dsacxz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true